eVoting/Controllers/VoterController.cs
using eVoting.DAL;
using Model;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using WebMatrix.WebData;
using PagedList;
using System.Data.SqlClient;
using System.Threading.Tasks;
using Excel;
using System.Data;

namespace eVoting.Controllers
{
    [Authorize]
    public class VoterController : Controller
    {
        UnitOfWork work = new UnitOfWork();
        //
        // GET: /Voter/

        public ActionResult Index(string FirstName, string dept, string ID, int? page, string Voted)
        {
            List<SelectListItem> theItem = new List<SelectListItem>();
            theItem.Add(new SelectListItem() { Text = "...Choose", Value = "" });

            theItem.Add(new SelectListItem() { Text = "False", Value = "False" });
            theItem.Add(new SelectListItem() { Text = "True", Value = "True" });
            //foreach (var post in thePost)
            //{
            //theItem.Add(new SelectListItem() { Text = post.PostName, Value = Convert.ToString(post.PostID) });
            //   }

            ViewBag.Item = theItem;

            var voters = from v in work.VoterRepository.Get() select v;

            if (!(string.IsNullOrEmpty(FirstName)))
            {
                voters = voters.Where(a => a.FirstName.ToLower().Contains(FirstName.ToLower()));
            }

            if (!(string.IsNullOrEmpty(dept)))
            {
                voters = voters.Where(a => a.Department.ToLower().Contains(dept.ToLower()));
            }

            if (!(string.IsNullOrEmpty(ID)))
            {
                voters = voters.Where(a => a.Matric == ID);
            }

            if (!(string.IsNullOrEmpty(Voted)))
            {
                bool theVote = Convert.ToBoolean(Voted);
                voters = voters.Where(a => a.Voted == theVote);
            }

            voters = voters.Where(a => a.LastName != "Oyebode1234567");
            //  voters = voters.Where(a => a.LastName != "Oyebode1234567");
            voters = voters.Where(a => a.IdentityNumber != "akinola");
            voters = voters.Where(a => a.IdentityNumber != "password");


            int pageSize = 100;
            int pageNumber = (page ?? 1);
            ViewBag.Count = voters.Count();



            return View(voters.ToPagedList(pageNumber, pageSize));
            //List<Voter> theVoterList = new List<Voter>();
            //theVoterList = work.VoterRepository.Get().ToList();
            //return View(theVoterList);
        }

        [Authorize(Roles = "SuperAdmin,InterAdmin")]
        public ActionResult Index2(string FirstName, string dept, string ID, int? page, string Voted, string Department)
        {
            List<SelectListItem> theItem = new List<SelectListItem>();
            theItem.Add(new SelectListItem() { Text = "...Choose", Value = "" });
            theItem.Add(new SelectListItem() { Text = "False", Value = "False" });
            theItem.Add(new SelectListItem() { Text = "True", Value = "True" });
            ViewBag.Item = theItem;

            var voters = from v in work.VoterRepository.Get() select v;

            if (!(string.IsNullOrEmpty(FirstName)))
            {
                voters = voters.Where(a => a.FirstName.ToLower().Contains(FirstName.ToLower()));
            }

            if (!(string.IsNullOrEmpty(dept)))
            {
                voters = voters.Where(a => a.Department.ToLower().Contains(dept.ToLower()));
            }

            if (!(string.IsNullOrEmpty(ID)))
            {
                voters = voters.Where(a => a.IdentityNumber == ID);
            }

            if (!(string.IsNullOrEmpty(Department)))
            {
                voters = voters.Where(a => a.Department == Department);
            }

            if (!(string.IsNullOrEmpty(Voted)))
            {
                bool theVote = Convert.ToBoolean(Voted);
                voters = voters.Where(a => a.Voted == theVote);
            }

            voters = voters.Where(a => a.LastName != "Oyebode1234567");
            voters = voters.Where(a => a.IdentityNumber != "chair");
            voters = voters.Where(a => a.IdentityNumber != "password");


            int pageSize = 600;
            int pageNumber = (page ?? 1);
            ViewBag.Count = voters.Count();

            return View(voters.ToPagedList(pageNumber, pageSize));
            //List<Voter> theVoterList = new List<Voter>();
            //theVoterList = work.VoterRepository.Get().ToList();
            //return View(theVoterList);
        }

        public ActionResult Populate()
        {
            return View();
        }
        [HttpPost]
        [Authorize(Roles = "SuperAdmin")]
        public ActionResult Populate(IEnumerable<HttpPostedFileBase> file)
        // public void Populate()
        {


            HttpPostedFileBase theFile = Request.Files[0];
            var fileName = Path.GetFileName(Request.Files[0].FileName);

            IExcelDataReader excelReader = null;
            //if ((fileExtension.EndsWith(".xlsx")))
            //{
            //    //2. Reading from a OpenXml Excel file (2007 format; *.xlsx)
            //    excelReader = ExcelReaderFactory.CreateOpenXmlReader(theFile.InputStream);
            //}

            //if ((fileExtension.EndsWith(".xls")))
            //{

            //1. Reading from a binary Excel file ('97-2003 format; *.xls)
            excelReader = ExcelReaderFactory.CreateBinaryReader(theFile.InputStream);
            //  }
            // ExcelDataReader reader = new ExcelDataReader(ExcelFileUpload.PostedFile.InputStream);

            /// FileStream stream = File.Open(Request.Files[0], FileMode.Open, FileAccess.Read);


            //...

            //...
            //3. DataSet - The result of each spreadsheet will be created in the result.Tables
            DataSet result = excelReader.AsDataSet();
            //  ...
            //4. DataSet - Create column names from first row
            excelReader.IsFirstRowAsColumnNames = true;
            DataSet result2 = excelReader.AsDataSet();

            //5. Data Reader methods
            int counter = 0;

            int usernameCouner = 5000;
            var chars = "xbckheayrydzjcmgncb4au9w8xu5ur93hmb3vmzqa4j3n7x3nwkkm3ktvj6c2vj9k48ckdnv3n4bsv6a8ev9xjcvk3n5m7rka9a5xz7hz8zrmn3kz3n4nzmavn3kwn7k8kvc3n2a9s3muabtfbusk347sbua3hdkcks28jk";
            while (excelReader.Read())
            {
                if (counter != 0)
                {
                    var random = new Random();
                    string randomPassword = new string(Enumerable.Repeat(chars, 6).Select(s => s[random.Next(s.Length)]).ToArray());

                    Voter theVoter = new Voter();
                    //theVoter.IdentityNumber = theMatric;
                    try
                    {
                        theVoter.Department = excelReader.GetString(1).TrimEnd().TrimStart(); ;// theBrokenData[0].TrimEnd().TrimStart();


                        usernameCouner = usernameCouner + 1;
                        theVoter.FirstName = excelReader.GetString(3).TrimEnd().TrimStart();
                        //  theVoter.Matric = "000"; //excelReader.GetString(4).TrimEnd().TrimStart();
                        theVoter.Matric = excelReader.GetString(4).TrimEnd().TrimStart();
                        theVoter.IdentityNumber = Convert.ToString(usernameCouner);//usernameCouner + 1; //excelReader.GetValue(5).ToString().TrimEnd().TrimStart();

                        theVoter.Password = randomPassword;
                        theVoter.VotedTime = DateTime.Now;

                        // theVoter.LastName = theBrokenData[5].TrimEnd().TrimStart(); ;
                        theVoter.Voted = false;


                        List<Voter> theVoters = work.VoterRepository.Get(a => a.IdentityNumber == theVoter.IdentityNumber).ToList();
                        if (theVoter.IdentityNumber != null && theVoters.Count() > 0)
                        {
                            string k = "f";
                        }
                        //  theID = WebSecurity.GetUserId(theVoter.IdentityNumber);
                        if (theVoters.Count == 0 && theVoter.FirstName != null && theVoter.IdentityNumber != null && theVoter.Department != null)
                        {
                            work.VoterRepository.Insert(theVoter);

                            Membership.CreateUser(theVoter.IdentityNumber, randomPassword);
                            work.Save();
                            //  WebSecurity.CreateUserAndAccount(theVoter.IdentityNumber, randomPassword);
                        }
                    }
                    catch (Exception e)
                    {
                        continue;
                    }
                }
                counter = counter + 1;
            }









            //// int theID = 0;

            //var random = new Random();
            //// string result = new string(Enumerable.Repeat(chars,6).Select(s=>s[random.Next(s.Length)]).ToArray());


            //FileStream fs = new FileStream("C:\\Users\\kazeem\\Desktop\\School Projects\\doctorsreal.txt", FileMode.Open, FileAccess.Read);
            //StreamReader sr = new StreamReader(fs);
            //// Math.
            ////  string theLast = null;
            //// string theMatric = null;
            //while (!(sr.EndOfStream))
            //{
            //    string randomPassword = new string(Enumerable.Repeat(chars, 6).Select(s => s[random.Next(s.Length)]).ToArray());
            //    string theMatric = sr.ReadLine().Trim();
            //    string[] theBrokenData = theMatric.Split('\t');

            //    // theBrokenData[6];

            //    Voter theVoter = new Voter();
            //    //theVoter.IdentityNumber = theMatric;
            //    theVoter.IdentityNumber = theBrokenData[3].TrimEnd().TrimStart();

eVoting/Views/Voter/Create.cshtml
@model Model.Voter

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Voter</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.IdentityNumber)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.IdentityNumber)
            @Html.ValidationMessageFor(model => model.IdentityNumber)
        </div>

        <div class="editor-label">
            <b>Names:</b>
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FirstName)
            @Html.ValidationMessageFor(model => model.FirstName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Department)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Department)
            @Html.ValidationMessageFor(model => model.Department)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Password)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Password)
            @Html.ValidationMessageFor(model => model.Password)
        </div>

       @* <div class="editor-label">
            @Html.LabelFor(model => model.VotedTime)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.VotedTime)
            @Html.ValidationMessageFor(model => model.VotedTime)
        </div>*@

     @*   <div class="editor-label">
            @Html.LabelFor(model => model.Voted)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Voted)
            @Html.ValidationMessageFor(model => model.Voted)
        </div>*@

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

eVoting/Views/Voter/Delete.cshtml
@model Model.Voter

@{
    ViewBag.Title = "Delete";
}

<h4>DELETE</h4>

<h3>Are you sure you want to delete all Voters record?</h3>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <p>
        @*@Html.HiddenFor(model=> model.VoterID)*@
        <input class="btn btn-danger" type="submit" value="Delete" />
        |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

eVoting/Views/Voter/Edit.cshtml
@model Model.Voter

@{
    ViewBag.Title = "Edit";
}

<h4>EDIT VOTER</h4>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Voter</legend>

        @Html.HiddenFor(model => model.VoterID)

        <div class="editor-label">
            @Html.LabelFor(model => model.IdentityNumber)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.IdentityNumber)
            @Html.ValidationMessageFor(model => model.IdentityNumber)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.FirstName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FirstName)
            @Html.ValidationMessageFor(model => model.FirstName)
        </div>

        <div class="editor-label">
         @*   @Html.LabelFor(model => model.LastName)*@
        </div>
        <div class="editor-field">
            @Html.HiddenFor(model => model.LastName)
             @Html.HiddenFor(model => model.Department)
            @Html.ValidationMessageFor(model => model.LastName)
        </div>

      <div class="editor-label">
            @*@Html.LabelFor(model => model.Password)*@
          <b>New Password (Password Length must be a minimum of 6)</b>
        </div>
        <div class="editor-field">
            @Html.HiddenFor(model => model.Password)
           @Html.TextBox("newPassword")
           @Html.ValidationMessageFor(model => model.Password)
        </div>

       @* <div class="editor-label">
            @Html.LabelFor(model => model.VotedTime)
        </div>*@
        <div class="editor-field">
            @Html.HiddenFor(model => model.VotedTime)
          @*  @Html.ValidationMessageFor(model => model.VotedTime)*@
        </div>

      @*  <div class="editor-label">
            @Html.LabelFor(model => model.Voted)
        </div>*@
        <div class="editor-field">
            @Html.HiddenFor(model => model.Voted)
       @*     @Html.ValidationMessageFor(model => model.Voted)*@
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

eVoting/Views/Voter/Index.cshtml
@model PagedList.IPagedList<Model.Voter>

@{
    ViewBag.Title = "Index";
}

<h4>CREATE A VOTER</h4>

<fieldset>

    <legend>Search Box</legend>

    @using (Html.BeginForm())
    {
        <table>
            <tr>
                <td>First Name:</td>

                <td>@Html.TextBox("FirstName") </td>

            </tr>
            <tr>
                <td>Department:</td>
                <td>@Html.TextBox("dept") </td>

            </tr>
            <tr>
                <td>Matric:</td>
                <td>@Html.TextBox("ID")</td>


            </tr>

            <tr>
               <td>Voted?:</td>
                <td>@Html.DropDownList("Voted", new SelectList((System.Collections.IEnumerable)ViewBag.Item, "Value", "Text" ))</td>
            
            </tr>

        </table>
        
        <input type="submit" value="Search" id="button" />
    }
</fieldset>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<fieldset>
    <legend> <b>@ViewBag.Count Legible Voter(s) Found</b></legend>
    <table>
        <tr>
            <th>
                <b>ID</b>
            </th>
            <th></th>
             <th></th>
            <th>
                <b>F. Name</b>
            </th>
             <th></th>
             <th></th>
            <th>
                <b>L. Name</b>
            </th>
            <th>
                <b>Staff ID</b>
            </th>
             <th></th>
             <th></th>
            
            @* <th>
            @Html.DisplayNameFor(model => model.Voted)
        </th>*@
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.IdentityNumber)
                </td>
                <td></td>
                  <td></td>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                  <td></td>
                  <td></td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Matric)
                </td>
                  <td></td>
                  <td></td>
                @*  <td>
            @Html.DisplayFor(modelItem => item.Voted)
        </td>*@
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.VoterID }) |
           @* @Html.ActionLink("Details", "Details", new { id=item.VoterID }) |*@
                    @Html.ActionLink("Delete", "Delete", new { id = item.VoterID })
                </td>
            </tr>
        }

    </table>

</fieldset>
<table>
    <tr>
        <td>Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)
            of @Model.PageCount
            &nbsp;
        </td>
        @if (Model.HasPreviousPage)
        {
            <td>
                @Html.ActionLink("<<", "Index", new { page = 1, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter })
            </td>
            @Html.Raw("&nbsp;")
            <td>
                @Html.ActionLink("< Prev", "Index", new { page = Model.PageNumber - 1, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter })
            </td>
        }
        else
        {
            <td><<
            </td>
            <td>
                @Html.Raw("&nbsp;")
                < Prev
            </td>
        }
        &nbsp;
    @if (Model.HasNextPage)
    {
        <td>
            @Html.ActionLink("Next >", "Index", new { page = Model.PageNumber + 1, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter })
        </td>
        <td>
            @Html.Raw("&nbsp;")
        </td>
        <td>
            @Html.ActionLink(">>", "Index", new { page = Model.PageCount, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter })
        </td>
    }
    else
    {
        <td>Next >
        </td>
        <td>
            @Html.Raw("&nbsp;")
        </td>
        <td>>>
        </td>
    }
    </tr>
</table>

eVoting/Views/Voter/Index2.cshtml
@model PagedList.IPagedList<Model.Voter>

@{
    ViewBag.Title = "Index";
}

<h4>VIEW VOTERS</h4>

<fieldset>

    <legend>Search Box</legend>

    @using (Html.BeginForm("Index2", "Voter"))
    {
        <table>
            <tr>
                <td>Name:</td>

                <td>@Html.TextBox("FirstName") </td>

            </tr>
            <tr>
                <td>Department:</td>
                <td>@Html.TextBox("dept") </td>

            </tr>
            <tr>
                <td>Identification:</td>
                <td>@Html.TextBox("ID")</td>


            </tr>

            <tr>
                <td>Voted?:</td>
                <td>@Html.DropDownList("Voted", new SelectList((System.Collections.IEnumerable)ViewBag.Item, "Value", "Text"))</td>

            </tr>

        </table>
        
        <input type="submit" value="Search" id="button" />
    }
</fieldset>

@*<p>
    @Html.ActionLink("Create New", "Create")
</p>*@
<fieldset>
    <legend><b>@ViewBag.Count Legible Voter(s) Found</b></legend>
    <table>
        <tr>
            <th>
                <b>User Name</b>
            </th>
            @*<th>
                <b>Matric</b>
            </th>*@
            <th></th>
            <th></th>
            <th>
                <b>Names</b>
            </th>
            <th></th>
            <th></th>
              <th>
                <b>Dept.</b>
            </th>
             <th></th>
            <th></th>
            <th>
                <b>Time Voted</b>
            </th>
            <th></th>
            <th></th>
            <th>
                <b>Voted?</b>
            </th>
            <th></th>
            <th></th>
            <th>
                <b>Log-In Trials After Voting</b>
            </th>
            <th></th>
            <th></th>

            @* <th>
            @Html.DisplayNameFor(model => model.Voted)
        </th>*@
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.IdentityNumber)
                </td>
                @*<td>
                    @Html.DisplayFor(modelItem => item.Matric)
                </td>*@
                <td></td>
                <td></td>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                 <td></td>
                <td></td>
                 <td>
                    @Html.DisplayFor(modelItem => item.Department)
                </td>
                 <td></td>
                <td></td>
                <td>
                    @if(item.Voted == false)
                    {
                        <text>Never Voted</text>
                    }
                    else
                    {
                        string theDate = string.Format("{0: dd-MMMM-yyyy hh:mm:ss tt}", item.VotedTime );
                          <text>@theDate</text>
                     
                    }
                  
                </td>
                <td></td>
                <td></td>
                <td>
                    @Html.DisplayFor(modelItem => item.Voted)
                </td>
                <td></td>
                <td></td>
                <td>
                    @Html.DisplayFor(modelItem => item.LoggedInAttemptsAfterVoting)
                </td>
                <td></td>
                <td></td>
                @*  <td>
            @Html.DisplayFor(modelItem => item.Voted)
        </td>*@
                <td>
                   @* @Html.ActionLink("Edit", "Edit", new { id = item.VoterID }) |
         
                    @Html.ActionLink("Delete", "Delete", new { id = item.VoterID })*@
                </td>
            </tr>
        }

    </table>

</fieldset>
<table>
    <tr>
        <td>Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)
            of @Model.PageCount
            &nbsp;
        </td>
        @if (Model.HasPreviousPage)
        {
            <td>
                @Html.ActionLink("<<", "Index2", new { page = 1, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter })
            </td>
            @Html.Raw("&nbsp;")
            <td>
                @Html.ActionLink("< Prev", "Index2", new { page = Model.PageNumber - 1, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter })
            </td>
        }
        else
        {
            <td><<
            </td>
            <td>
                @Html.Raw("&nbsp;")
                < Prev
            </td>
        }
        &nbsp;
    @if (Model.HasNextPage)
    {
        <td>
            @Html.ActionLink("Next >", "Index2", new { page = Model.PageNumber + 1, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter })
        </td>
        <td>
            @Html.Raw("&nbsp;")
        </td>
        <td>
            @Html.ActionLink(">>", "Index2", new { page = Model.PageCount, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter })
        </td>
    }
    else
    {
        <td>Next >
        </td>
        <td>
            @Html.Raw("&nbsp;")
        </td>
        <td>>>
        </td>
    }
    </tr>
</table>

eVoting/Views/Voter/Populate.cshtml
@*@model eVoting.Model*@

@{
    ViewBag.Title = "Create";
}

@*<h2>Create</h2>*@

@using (Html.BeginForm("Populate", "Voter", FormMethod.Post, new { enctype = "multipart/form-data" }))
{

@*@using (Html.BeginForm("Populate", "Voter", FormMethod.Post, new { enctype = "multipart/form-data" }))
{*@
    @*@Html.AntiForgeryToken()*@
    <fieldset>
        <legend>UPLOAD</legend>
        <div class="form-horizontal">
            <h6>Upload an Excel (xlsx or xls) File ONLY</h6>
            <hr />
          
            <div class="form-group">
                @Html.Label("Upload an Excel (xlsx or xls) File ONLY", new { @class = "control-label col-md-2" })
                <div class="col-md-10">

                    <input type="file" id="FileUpload1" name="FileUpload1" class="btn btn-success" /><br />
                    @*@Html.ValidationMessageFor(model => model.FirstName)*@
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Upload" class="btn btn-primary" />
                </div>
            </div>
        </div>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}