eVoting/Controllers/ParticipantController.cs
using eVoting.DAL;
using Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;

namespace eVoting.Controllers
{
    [Authorize]
    public class ParticipantController : Controller
    {
        //
        // GET: /Participant/
        UnitOfWork work = new UnitOfWork();

        public ActionResult Index(string FirstName, string LastName, string MiddleName, int? page, string Post)
        {
            var candidate = from c in work.ParticipantRepository.Get() select c;

            if (!(string.IsNullOrEmpty(FirstName)))
            {
                candidate = candidate.Where(a => a.FirstName.ToLower().Contains(FirstName.ToLower()));
            }

            if (!(string.IsNullOrEmpty(LastName)))
            {
                candidate = candidate.Where(a => a.LastName.ToLower().Contains(LastName.ToLower()));
            }

            if (!(string.IsNullOrEmpty(MiddleName)))
            {
                candidate = candidate.Where(a => a.MiddleName.ToLower().Contains(MiddleName.ToLower()));
            }

            if (!(string.IsNullOrEmpty(Post)))
            {
                int thePostID = Convert.ToInt32(Post);
                candidate = candidate.Where(a => a.PostID == thePostID);
            }

            List<Post> thePost = work.PostRepository.Get().ToList();
            List<SelectListItem> theItem = new List<SelectListItem>();

            theItem.Add(new SelectListItem() { Text = "...Choose", Value = "" });
            foreach (var post in thePost)
            {
                theItem.Add(new SelectListItem() { Text = post.PostName, Value = Convert.ToString(post.PostID) });
            }

            ViewBag.Item = theItem;

            int pageSize = 100;
            int pageNumber = (page ?? 1);
            ViewBag.Count = candidate.Count();



            return View(candidate.ToPagedList(pageNumber, pageSize));
        }

        //
        // GET: /Participant/Details/5

        public ActionResult Details(int id)
        {
            Participant theParticipant = work.ParticipantRepository.GetByID(id);

            Post thePost = work.PostRepository.GetByID(theParticipant.PostID);
            ViewBag.PostName = thePost.PostName;

            return View(theParticipant);
        }

        //
        // GET: /Participant/Create

        public ActionResult Create()
        {
            List<Post> thePosts = work.PostRepository.Get().ToList();
            List<SelectListItem> theItems = new List<SelectListItem>();

            foreach (var item in thePosts)
            {
                theItems.Add(new SelectListItem() { Text = item.PostName, Value = Convert.ToString(item.PostID) });

            }
            ViewBag.Item = theItems;
            return View();
        }

        [AcceptVerbs(HttpVerbs.Get)]
        public FileContentResult GetImage(int id)
        {
            //PrimarySchoolStudent theStudent = work.PrimarySchoolStudentRepository.GetByID(id);
            //   Book theBook = work.BookRepository.GetByID(id);
            Photo thePhoto = work.PhotoRepository.Get(a => a.ParticipantID == id).First();
            // Photo myPhoto = thePhoto[0];


            return File(thePhoto.FileData, "image/png");

        }

        //
        // POST: /Participant/Create

        [HttpPost]
        public ActionResult Create(Participant model)
        {
            try
            {
                // int thePostID = model.Post.PostID;
                // model.PostID = thePostID;
                if (ModelState.IsValid)
                {
                    work.ParticipantRepository.Insert(model);
                    work.Save();
                }
                // TODO: Add insert logic here


                return RedirectToAction("Create", "Photo", new { id = model.ParticipantID });
                // return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Participant/Edit/5

        public ActionResult Edit(int id)
        {
            Participant theParticipant = work.ParticipantRepository.GetByID(id);
            List<Post> thePosts = work.PostRepository.Get().ToList();
            List<SelectListItem> theItems = new List<SelectListItem>();

            foreach (var item in thePosts)
            {
                theItems.Add(new SelectListItem() { Text = item.PostName, Value = Convert.ToString(item.PostID) });

            }
            ViewBag.Item = theItems;
            return View(theParticipant);
        }

        //
        // POST: /Participant/Edit/5

        [HttpPost]
        public ActionResult Edit(Participant model)
        {
            try
            {
                // TODO: Add update logic here
                // int thePostID = model.Post.PostID;
                // model.PostID = thePostID;
                if (ModelState.IsValid)
                {
                    work.ParticipantRepository.Update(model);
                    work.Save();
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Participant/Delete/5

        public ActionResult Delete(int id)
        {
            Participant theParticipant = work.ParticipantRepository.GetByID(id);
            return View(theParticipant);
        }

        public ActionResult Restore()
        {
            List<Participant> theParticipant = work.ParticipantRepository.Get().ToList();
            var context = new evContext();
            foreach (Participant p in theParticipant)
            {
                Participant thePar = context.Participants.Find(p.ParticipantID);
                thePar.No = 0;
                thePar.Yes = 0;
                thePar.Vote = 0;


              //  work.ParticipantRepository.Update(p);
            }
            context.SaveChanges();
            context.Dispose();
            return RedirectToAction("View");
        }

        //
        // POST: /Participant/Delete/5

        [HttpPost]
        public ActionResult Delete(Participant model)
        {
            try
            {
                int theID = model.ParticipantID;
                Participant theParticipant = work.ParticipantRepository.GetByID(theID);

                work.ParticipantRepository.Delete(theParticipant);
                work.Save();
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

eVoting/Controllers/PostController.cs
using eVoting.DAL;
using iTextSharp.text;
using iTextSharp.text.pdf;
using Model;
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using WebMatrix.WebData;

namespace eVoting.Controllers
{
    //[ConcurrencyCheck]   
    [Authorize]
    public class PostController : Controller
    {
        UnitOfWork work = new UnitOfWork();
        //
        // GET: /Post/

        public ActionResult Index()
        {
            // work.PostRepository.Get().ToList();
            return View(work.PostRepository.Get().ToList());
        }

        //
        // GET: /Post/Details/5

        public ActionResult Details(int id)
        {
            // evContext con = new evContext();
            // con.Posts.Include(d=>d.)

            Post thePost = work.PostRepository.GetByID(id);
            int thePostId = thePost.PostID;
            List<Participant> theParticipants = work.ParticipantRepository.Get(a => a.PostID == thePostId).ToList();
            ViewBag.Participant = theParticipants;
            return View(thePost);
        }

        //
        // GET: /Post/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Post/Create

        [HttpPost]
        //public ActionResult Create(FormCollection collection)
        public ActionResult Create(Post model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    work.PostRepository.Insert(model);
                    work.Save();
                }
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Post/Edit/5

        public ActionResult Edit(int id)
        {
            Post thePost = work.PostRepository.GetByID(id);

            return View(thePost);
        }

        public ActionResult Vote()
        {
            // evContext ev = new evContext();
            ///  ev.Posts.Include(as=).
            List<Post> thePosts = work.PostRepository.Get().ToList();

            // List<Participant> theParticipants = work.ParticipantRepository.Get(a => a.PostID == 2).ToList();
            //foreach (var post in thePosts)
            //{
            //    List<Participant> theParticipants = work.ParticipantRepository.Get(a => a.PostID == post.PostID).ToList();
            //    ViewBag.Participant = theParticipants;
            //}
            //int thePostId = thePost.PostID;
            //List<Participant> theParticipants = work.ParticipantRepository.Get(a => a.PostID == thePostId).ToList();
            //ViewBag.Participant = theParticipants;

            return View("Vote", thePosts);
        }
        [Authorize]
        public ActionResult Voted(string PRESIDENT, string VICE_PRESIDENT, string GENERAL_SECRETARY,
            string ASST_GENERAL_SECRETARY, string FINANCIAL_SECRETARY, string TREASURER, string PUBLIC_RELATIONS_OFFICER,
            string SOCIAL_DIRECTOR, string WELFARE_OFFICER, string SPORT_DIRECTOR, string ASST_SPORT_DIRECTOR, string SOCIAL_OFFICER_MALE,
           string SOCIAL_OFFICER_FEMALE, string SPORTS_OFFICER_MALE, string SPORTS_OFFICER_FEMALE, string theKey)
        {
           

            long theCounter = Convert.ToInt64(theKey);
            if (theCounter > 0)
            {
                //   var future = new Date("Dec 3 2013 21:15:00 GMT+0200");
                // var now = new Date();
                // var difference = Math.floor((future.getTime() - now.getTime()) / 1000);
                //@Html.Raw(theParticipants[0].ParticipantID + ":" + "YES")
                //PRESIDENT
                // VICE_PRESIDENT
                //GENERAL_SECRETARY
                //ASSISTANT_GENERAL_SECRETARY
                //FINANCIAL_SECRETARY
                //TREASURER
                //PUBLIC_RELATIONS_OFFICER
                var context = new evContext();
                // using (var context = new evContext())
                // {

                // context.

                //president
                int pre = 0;
                if (!(string.IsNullOrEmpty(PRESIDENT)))
                {
                    string[] c = PRESIDENT.Split(':');
                    if (c.Count() == 1)
                    {
                        pre = Convert.ToInt32(PRESIDENT);
                        // Participant thePar = work.ParticipantRepository.GetByID(pre);
                        Participant thePar = context.Participants.Find(pre);
                        thePar.Vote = thePar.Vote + 1;
                    }
                    if (c.Count() == 2)
                    {
                        //@Html.Raw(theParticipants[0].ParticipantID + ":" + "YES")
                        pre = Convert.ToInt32(c[0]);
                        // Participant thePar = work.ParticipantRepository.GetByID(pre);
                        Participant thePar = context.Participants.Find(pre);
                        if (c[1] == "YES")
                        {
                            thePar.Yes = thePar.Yes + 1;
                        }
                        if (c[1] == "NO")
                        {
                            thePar.No = thePar.No + 1;
                        }

                    }
                    //  context.Participants.sa
                    // work.ParticipantRepository.Update(thePar);
                    // work.Save();
                }


                //vp
                int vp = 0;
                if (!(string.IsNullOrEmpty(VICE_PRESIDENT)))
                {
                    string[] c = VICE_PRESIDENT.Split(':');
                    if (c.Count() == 1)
                    {
                        vp = Convert.ToInt32(VICE_PRESIDENT);
                        Participant vpPar = context.Participants.Find(vp);
                        vpPar.Vote = vpPar.Vote + 1;
                    }
                    if (c.Count() == 2)
                    {
                        vp = Convert.ToInt32(c[0]);
                        Participant vpPar = context.Participants.Find(vp);
                        if (c[1] == "YES")
                        {
                            vpPar.Yes = vpPar.Yes + 1;
                        }
                        if (c[1] == "NO")
                        {
                            vpPar.No = vpPar.No + 1;
                        }
                    }
                    //   work.ParticipantRepository.Update(vpPar);
                    // work.Save();
                }

                //gs
                int gn = 0;
                if (!(string.IsNullOrEmpty(GENERAL_SECRETARY)))
                {
                    string[] c = GENERAL_SECRETARY.Split(':');
                    if (c.Count() == 1)
                    {
                        gn = Convert.ToInt32(GENERAL_SECRETARY);
                        Participant vpPar = context.Participants.Find(gn);
                        vpPar.Vote = vpPar.Vote + 1;
                    }
                    if (c.Count() == 2)
                    {
                        gn = Convert.ToInt32(c[0]);
                        Participant vpPar = context.Participants.Find(gn);
                        if (c[1] == "YES")
                        {
                            vpPar.Yes = vpPar.Yes + 1;
                        }
                        if (c[1] == "NO")
                        {
                            vpPar.No = vpPar.No + 1;
                        }
                    }
                    //  work.ParticipantRepository.Update(vpPar);
                    //  work.Save();

                }


                //ags
                int ags = 0;
                if (!(string.IsNullOrEmpty(ASST_GENERAL_SECRETARY)))
                {
                    string[] c = ASST_GENERAL_SECRETARY.Split(':');
                    if (c.Count() == 1)
                    {
                        ags = Convert.ToInt32(ASST_GENERAL_SECRETARY);
                        Participant Par = context.Participants.Find(ags);
                        Par.Vote = Par.Vote + 1;
                    }
                    if (c.Count() == 2)
                    {
                        ags = Convert.ToInt32(c[0]);
                        Participant Par = context.Participants.Find(ags);
                        if (c[1] == "YES")
                        {
                            Par.Yes = Par.Yes + 1;
                        }
                        if (c[1] == "NO")
                        {
                            Par.No = Par.No + 1;
                        }
                    }
                    //  work.ParticipantRepository.Update(Par);
                    //  work.Save();

                }

                //pro
                int pro = 0;
                if (!(string.IsNullOrEmpty(PUBLIC_RELATIONS_OFFICER)))
                {
                    string[] c = PUBLIC_RELATIONS_OFFICER.Split(':');
                    if (c.Count() == 1)
                    {
                        pro = Convert.ToInt32(PUBLIC_RELATIONS_OFFICER);
                        Participant Par = context.Participants.Find(pro);
                        Par.Vote = Par.Vote + 1;
                    }
                    if (c.Count() == 2)
                    {
                        pro = Convert.ToInt32(c[0]);
                        Participant Par = context.Participants.Find(pro);
                        if (c[1] == "YES")
                        {
                            Par.Yes = Par.Yes + 1;
                        }
                        if (c[1] == "NO")
                        {
                            Par.No = Par.No + 1;
                        }
                    }
                    // work.ParticipantRepository.Update(Par);

eVoting/Views/Post/Create.cshtml
@model Model.Post

@{
    ViewBag.Title = "Create";
}

<h4>CREATE NEW POST</h4>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Post</legend>

        <div class="editor-label">
          <b>Post Name</b>
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.PostName)
            @Html.ValidationMessageFor(model => model.PostName)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

eVoting/Views/Post/Delete.cshtml
@model Model.Post

@{
    ViewBag.Title = "Delete";
}

<h4>DELETE POST</h4>

<h3>Are you sure you want to delete this POST?</h3>
<fieldset>
    <legend>Post</legend>

    <div class="display-label">
       <b>Post Name</b>  
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PostName)
    </div>
</fieldset>
@using (Html.BeginForm()) {
       @Html.HiddenFor(model => model.PostID)
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

eVoting/Views/Post/Details.cshtml
@model Model.Post

@{
    ViewBag.Title = "Details";
}

<h4>POST DETAILS</h4>

<fieldset>
    <legend>Post</legend>

    <div class="display-label">
        <b>Post Name</b>
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PostName)
    </div>
    <b>Candidates Registered for Post </b>
    <br />

    <table>

        @foreach (var candidate in ViewBag.Participant)
        {
            <tr>
                <td>@candidate.LastName   @candidate.FirstName  @candidate.MiddleName</td>
            </tr>
        }

    </table>
</fieldset>
<p>
    @* @Html.ActionLink("Edit", "Edit", new { id=Model.PostID }) |*@
    @Html.ActionLink("Back to List", "Index")
</p>

eVoting/Views/Post/Edit.cshtml
@model Model.Post

@{
    ViewBag.Title = "Edit";
}

<br />

<h4>EDIT POST</h4>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Post</legend>

        @Html.HiddenFor(model => model.PostID)

        <div class="editor-label">
            <b>Post Name</b>
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.PostName)
            @Html.ValidationMessageFor(model => model.PostName)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

eVoting/Views/Post/Index.cshtml
@model IEnumerable<Model.Post>

@{
    ViewBag.Title = "Index";
}

<h4>LIST OF POSTS</h4>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            <b>Post Name</b>
          @*  @Html.DisplayNameFor(model => model.PostName)*@
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.PostName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.PostID }) |
            @Html.ActionLink("Details", "Details", new { id=item.PostID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.PostID })
        </td>
    </tr>
}

</table>

eVoting/Views/Post/PasswordCheck.cshtml
@model IEnumerable<Model.Voter>

@{
    ViewBag.Title = "PasswordCheck";
}

<h4>CHECK VOTER'S PASSWORD</h4>

<br />
<br />

@using (Html.BeginForm())
{
    <fieldset>
        <legend>Search Box</legend>

        <table>



            <tr>

                <td>
                    <b>MATRIC NUMBER:</b>
                </td>
                <td>
                    @Html.TextBox("MatNumber") &nbsp;
                </td>
            </tr>



        </table>
        <input type="submit" value="Search" id="button" />
        <br />
    </fieldset>
}
    @Html.ActionLink("Print-PassWord","PrintPassword","Post", new{@class="btn-primary"})

@*<p>
    @Html.ActionLink("Create New", "Create")
</p>*@
<table>
    <tr>
        <th>
           <b>ID.</b>
        </th>
        <th>
        </th>
         <th>
        </th>
        <th>
           <b>Name</b>
        </th>
         <th>
        </th>
         <th>
        </th>
        <th>
           <b>Department</b>
        </th>
         <th>
        </th>
         <th>
        </th>
        <th>
           <b>Password</b>
        </th>
         <th>
        </th>
         <th>
        </th>
        <th>
           <b>Voted Time</b>
        </th>
         <th>
        </th>
         <th>
        </th>
        <th>
           <b>Voted?</b>
        </th>
        <th></th>
    </tr>

   
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdentityNumber)
            </td>
            <td></td>
             <td></td>
             <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
             <td></td>
             <td></td>
             <td>
                @Html.DisplayFor(modelItem => item.Department)
            </td>
             <td></td>
             <td></td>
            <td>
              <h3> <b> @Html.DisplayFor(modelItem => item.Password) </b></h3>
            </td>
             <td></td>
             <td></td>
            <td>
                @if (item.Voted == true)
                {
                  string theDate =  string.Format("{0:ddd, MMM, yyyy h:mm:ss tt}",item.VotedTime);
                      @* @Html.DisplayFor(modelItem => item.VotedTime)*@
                  <text>@theDate</text>
                    
                }
                else
                {
                    <text>Never Voted</text>
                }
             
               @* @ViewBag.DateTime*@
            </td>
             <td></td>
             <td></td>
            <td>
                @Html.DisplayFor(modelItem => item.Voted)
            </td>

           @* <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.VoterID }) |
            @Html.ActionLink("Details", "Details", new { id = item.VoterID }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.VoterID })
            </td>*@
        </tr>
    }
    

</table>

eVoting/Views/Post/Result.cshtml
@model IEnumerable<Model.Post>

@{
    ViewBag.Title = "Result";
    eVoting.DAL.UnitOfWork work = new eVoting.DAL.UnitOfWork();
}

@{
 


TimeZoneInfo est = TimeZoneInfo.FindSystemTimeZoneById("W. Central Africa Standard Time");

DateTime da = TimeZoneInfo.ConvertTime(DateTime.Now,est);
string dat = string.Format("{0:dd-MMMM-yyyy   hh:mmtt}", da);
}
<h2>ELECTION RESULTS      <text>( @dat)</text> </h2>
<br />
@*<fieldset>
    <legend>Post</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.PostName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PostName)
    </div>
</fieldset>*@

@foreach (var post in Model)
{
    List<Model.Participant> theParticipants = work.ParticipantRepository.Get(a => a.PostID == post.PostID).OrderBy(a=>a.LastName).ToList();
    <fieldset> 
        <legend><h4>@post.PostName</h4></legend>

        @if (theParticipants.Count > 1)
        {
            foreach (var man in theParticipants)
            {
            <img src="@Url.Action("GetImage", "Participant", new { id = man.ParticipantID })"  width="70" height="70" /> <text>@man.MiddleName @man.LastName @man.FirstName  <b>Scored </b>- <b>@man.Vote</b></text>
                


            <br />
            <hr />
            }
        }
        @if (theParticipants.Count == 1)
        {
        
            <div>
                <img src="@Url.Action("GetImage", "Participant", new { id = theParticipants[0].ParticipantID })"  width="70" height="70" />
                <br />
                <b>@theParticipants[0].LastName @theParticipants[0].FirstName @theParticipants[0].MiddleName </b>
              <br />
                 <text> <b>YES VOTE(S) - </b> <b>@theParticipants[0].Yes</b></text>
                 <br />
                <text> <b>NO VOTE(S) - </b> <b>@theParticipants[0].No</b></text>
                @* <input type="radio" name="@Html.Raw(man.Post.PostName)" value="@Html.Raw(man.ParticipantID)"/><b>@Html.Raw(man.LastName + "  ")@Html.Raw(man.FirstName + "  ")@Html.Raw(man.MiddleName + "  ")</b>*@

              @*  <input type="radio" name="@Html.Raw(post.PostName)" value="@Html.Raw(theParticipants[0].ParticipantID + ":" + "YES")"/><b>YES</b>
                <input type="radio" name="@Html.Raw(post.PostName)" value="@Html.Raw(theParticipants[0].ParticipantID + ":" + "NO")"/><b>NO</b>*@
                <hr />
            </div>
        }


    </fieldset>
    <br />
    <br />
}

<h4><b>@ViewBag.NumberVoted Voted out of   @ViewBag.TotalVoter  Registered Voters</b></h4>
<p>
    @*  @Html.ActionLink("Edit", "Edit", new { id=Model.PostID }) |
    @Html.ActionLink("Back to List", "Index")*@
</p>

eVoting/Views/Post/Vote.cshtml
@model IEnumerable<Model.Post>

@{
    ViewBag.Title = "Vote";
    eVoting.DAL.UnitOfWork work = new eVoting.DAL.UnitOfWork();
}

<h1>VOTE FOR CHANGE!</h1>
<br />

@using (Html.BeginForm("Voted", "Post"))
{
    @Html.ValidationSummary(true)
    @Html.Hidden("theKey")

@*<fieldset>
        <legend>Post</legend>*@
  

    foreach (var post in Model)
    {
        List<Model.Participant> theParticipants = work.ParticipantRepository.Get(a => a.PostID == post.PostID).OrderBy(a=>a.LastName).ToList();
    <fieldset>
        <legend>Position -<b>@post.PostName</b></legend>
        @if (theParticipants.Count > 1)
        {
            foreach (var man in theParticipants)
            {

            <div>
                <img src="@Url.Action("GetImage", "Participant", new { id = man.ParticipantID })"  width="80" height="80" />
                @* <input type="radio" name="@Html.Raw(man.Post.PostName)" value="@Html.Raw(man.ParticipantID)"/><b>@Html.Raw(man.LastName + "  ")@Html.Raw(man.FirstName + "  ")@Html.Raw(man.MiddleName + "  ")</b>*@
                <input type="radio" name="@Html.Raw(post.PostName)" value="@Html.Raw(man.ParticipantID)"/><b>@Html.Raw(man.MiddleName + "  ")@Html.Raw(man.LastName + "  ")@Html.Raw(man.FirstName + "  ")</b>
                <hr />
            </div>
            }

        }
        @if (theParticipants.Count == 1)
        {
        
        <div>
            <img src="@Url.Action("GetImage", "Participant", new { id = theParticipants[0].ParticipantID })"  width="80" height="80" />
            <br />
           <b> @Html.Raw(theParticipants[0].MiddleName + "  ")@Html.Raw(theParticipants[0].LastName + "  ")@Html.Raw(theParticipants[0].FirstName + "  ")</b>
            <br />
            <b>Candidate is UNOPPOSED, Vote YES to support or NO to reject Candidate</b>
            <br />
              <br />
            @* <input type="radio" name="@Html.Raw(man.Post.PostName)" value="@Html.Raw(man.ParticipantID)"/><b>@Html.Raw(man.LastName + "  ")@Html.Raw(man.FirstName + "  ")@Html.Raw(man.MiddleName + "  ")</b>*@
            <input type="radio" name="@Html.Raw(post.PostName)" value="@Html.Raw(theParticipants[0].ParticipantID + ":" + "YES")"/><b>YES</b>
            
             <br />
             <br />
            <input type="radio" name="@Html.Raw(post.PostName)" value="@Html.Raw(theParticipants[0].ParticipantID + ":" + "NO")"/><b>NO</b>
            <hr />
        </div>
        }

        @*man.CandidateId*@




    </fieldset>
    <br />
    <br />
    <br />
    <br>
    }

@* <div class="editor-label">
            @Html.LabelFor(model => model.PostName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.PostName)
            @Html.ValidationMessageFor(model => model.PostName)
        </div>*@

    <p>
        <input class="btn btn-primary" type="submit" value="Submit Vote" />
    </p>@*
    </fieldset>*@
}



@*<div>
    @Html.ActionLink("Back to List", "Index")
</div>*@

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">

        document.onkeydown = cancelArrowKeys;

        function cancelArrowKeys(e) {
            try {
                var e = window.event || e




                var key = e.charCode ? e.charCode : e.keyCode ? e.keyCode : 0;

                event.returnValue = false;


                //if (key == 37 || key == 38 || key == 39 || key == 40 || key == 13) {
                //    if (key == 13)
                //        document.getElementById('<%=btnFightPokemon.ClientID%>').click();
                //    if (key == 37)
                //        document.getElementById('<%=ImgBtnWest.ClientID%>').click();
                //    if (key == 38)
                //        document.getElementById('<%=ImgBtnNorth.ClientID%>').click();
                //    if (key == 39)
                //        document.getElementById('<%=ImgBtnEast.ClientID%>').click();
                //    if (key == 40)
                //        document.getElementById('<%=ImgBtnSouth.ClientID%>').click();



                //}
            }
            catch (Exception) {
                return false;
            }

           
        }
        //var future = new Date("Dec 15 2017 16:00:00 GMT+0100");
       // var future = new Date("Oct 25 2018 16:00:00 GMT+0100");
       // var future = new Date("Oct 27 2018 16:00:00 GMT+0100");
        var future = new Date("Dec 21 2018 15:00:00 GMT+0100");
        ////var future = new Date("Dec 13 2013 17:00:00 GMT+0100");

      //  var future = new Date("Jan 19 2017 15:00:00 GMT+0100");
        //var future = new Date("Dec 13 2013 17:00:00 GMT+0100");
        var now = new Date();
       // var now = now.toUTCString()
        var difference = Math.floor((future.getTime() - now.getTime()) / 1000);
        $('#theKey').val(difference);

       // alert($('#theKey').val());
        //document.onkeydown = kd;

        //function kd() {
        //  //  alert("Hello");
        //    event.returnValue = false;

        //}
    </script>

}